version: '3'

services:
  transactional:
    image: postgres:12
    environment:
      POSTGRES_DB: dvdrental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./data/dvdrental.sql:/docker-entrypoint-initdb.d/dvdrental.sql
    ports:
      - 5432:5432

  analytics:
    image: postgres:12
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5440:5432

  python:
    image: python:3.8-slim
    command: bash -c "apt-get update && apt-get install -y python3"
    volumes:
      - ./python:/app

volumes:
    postgres: